.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DU" "1" "March 2015" "" ""
.
.SH "NAME"
\fBdu\fR \- 报告磁盘空间使用情况
.
.SH "描述"
du会显示指定的目录或文件所占用的磁盘空间\.在没给定参数的情况下,du报告当前 目录所使用的磁盘空间\.
.
.SH "语法"
\fBdu [OPTION]\.\.\. [FILE]\.\.\.\fR
.
.P
\fBdu [OPTION]\.\.\. \-\-files0\-from=F\fR
.
.SH "参数"
.
.TP
\fB\-a 或 \-all\fR
显示目录中个别文件的大小\.
.
.TP
\fB\-b 或 \-bytes\fR
显示目录或文件大小时,以byte为单位\.
.
.TP
\fB\-c 或 \-\-total\fR
除了显示个别目录或文件的大小外,同时也显示所有目录或文件的总和\.
.
.TP
\fB\-D 或 \-\-dereference\-args\fR
显示指定符号连接的源文件大小\.
.
.TP
\fB\-h 或 \-\-human\-readable\fR
以K,M,G为单位,提高信息的可读性\.
.
.TP
\fB\-H 或 \-\-si\fR
与\-h参数相同,但是K,M,G是以1000为换算单位\.
.
.TP
\fB\-k 或 \-\-kilobytes\fR
以1024 bytes为单位\.
.
.TP
\fB\-l 或 \-\-count\-links\fR
重复计算硬件连接的文件\.
.
.TP
\fB\-L 或 \-\-dereference\fR
显示指定符号连接的源文件大小\.
.
.TP
\fB\-m\fR
以1MB为单位\.
.
.TP
\fB\-s 或 \-\-summarize\fR
仅显示总计\.
.
.TP
\fB\-S 或 \-\-separate\-dirs\fR
显示个别目录的大小时,并不含其子目录的大小\.
.
.TP
\fB\-x 或 \-\-one\-file\-xystem\fR
以开始处理时的文件系统为准,若遇上其它不同的文件系统目录则略过\.
.
.TP
\fB\-X 或 \-\-exclude\-from=file\fR
在file指定目录或文件\.
.
.TP
\fB\-\-exclude=file\fR
略过指定的目录或文件\.
.
.TP
\fB\-\-max\-depth=N\fR
超过指定层数的目录后,予以忽略\.
.
.TP
\fB\-\-help\fR
显示帮助\.
.
.TP
\fB\-\-version\fR
显示版本信息\.
.
.SH "版权"
由\fIhttp://linux\.sheup\.com/linux/4/31055\.html\fR整理而来\.
