.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ECHO" "1" "February 2015" "" ""
.
.SH "NAME"
\fBecho\fR \- 显示一行文本
.
.SH "描述"
将字符串STRING(s)显示到标准输出
.
.SH "格式SYNOPSIS"
\fBecho [<\-n>] 字符串\fR
.
.P
字符串可以加引号，也可以不加引号。用echo命令输出加引号的字符串时，将字符 串原样输出；用echo命令输出不加引号的字符串时，将字符串中的各个单词作为字 符串输出，各字符串之间用一个空格分割。
.
.P
如果使用了\fB\-n\fR选项，在兼容\fBXSI(X/Open System Interfaces Extension)\fR的系 统下，下列符号将会被识别并重定义：
.
.IP "" 4
.
.nf

\ea  发出警告声
\eb  删除前一个字符
\ec  最后不加上换行符号
\ef  换行但光标仍旧停留在原来的位置
\en  换行且光标移至行首
\er  光标移至行首，但不换行
\et  插入Tab
\ev  与\ef相同
\e\e  插入\e字符
\e0nnn   插入八进制数NNN（1到3位）表示的ASCII字节
.
.fi
.
.IP "" 0
.
.P
提醒：你的shell可能有其自己版本的echo命令。该命令通常会取代此处描述的版 本。具体请参阅你的shell的文档以了解它所支持的选项。
.
.P
本程序的完整文档使用Texinfo手册进行维护。如果info和本程序已经正确地安装 在了你的电脑上，通过下述命令
.
.IP "" 4
.
.nf

info coreutils \'echo invocation\'
.
.fi
.
.IP "" 0
.
.P
可以访问完整的使用手册。
.
.SH "范例EXAMPLES"
.
.nf

将hello输出到终端

echo hello

将hello保存到文件file中，如果没有文件会新建一个文件。如果已经有
文件则会覆盖以前的文件

echo hello >file

将结果追加到文件file中

echo hello >>file
.
.fi
.
.SH "版权COPYRIGHT"

