.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FREE" "1" "March 2015" "" ""
.
.SH "NAME"
\fBfree\fR \- − 显示系统中已用和未用的内存空间总和
.
.SH "总览"
\fBfree [−b | −k | −m] [−o] [−s delay] [−t] [−V]\fR
.
.SH "描述"
free是一个用来获得内存使用概况的快速简单的方法,信息从"/proc/meminfo"中 获取\.它提供了一个快照,用于展示总计/闲置的物理内存和系统交换区,以及已使 用/闲置的内核缓冲区\.free输出的列表如下:
.
.IP "" 4
.
.nf

total:物理内存总量(= used + free, =MemTotal + SwapTotal)
used:已分配的内存(= total \- free \- buffers \- cache)
free:未被分配的内存(= MemFree + SwapFree)
shared:共享内存,主要被tmpfs使用(= Shmem)
buffers:块设备缓存区(= Buffers)
cached:文件缓存(= Cached + Slab)
available:可用于启动新程序的内存总量,不包括swap
.
.fi
.
.IP "" 0
.
.SH "选项"
.
.TP
\fB\-b, \-\-bytes\fR
以字节为单位显示内存总和,"\fB\-k, \-\-kilo\fR"以KB为单位显示,"\fB\-m, \-\-mega\fR" 以MB为单位显示,"\fB\-g, \-\-giga\fR"选项以GB为单位显示,"\fB\-\-tera\fR"选项以TB为 单位显示\.默认为KB\.
.
.TP
\fB\-h, \-\-human\fR
以适于人类可读方式显示内存信息
.
.TP
\fB\-t, \-\-total\fR
显示全部内存
.
.TP
\fB\-s, \-\-seconds N\fR
使free以N秒为间隔,连续抽样显示\.N可以设置成浮点数,它用usleep(3)做 微秒级延迟\.
.
.TP
\fB\-c, \-\-count N\fR
Display the result count times\. Requires the \-s option\.
.
.TP
\fB\-w, \-\-wide\fR
Switch to the wide mode\. The wide mode produces lines longer than 80 characters\. In this mode buffers and cache are reported in two separate columns\.
.
.TP
\fB\-l, \-\-lohi\fR
显示高低内存利用率
.
.TP
\fB\-\-si\fR
Use power of 1000 not 1024\.
.
.TP
\fB−V\fR
显示版本信息
.
.SH "范例"
每3秒统计一次内存利用率人类可读，并且一共显示两次
.
.IP "" 4
.
.nf

$ free \-hs 3 \-c 2
.
.fi
.
.IP "" 0
.
.SH "文件"
/proc/meminfo \-\- 内存信息
.
.SH "参考"
ps(1), top(1)
