.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ICONV" "1" "March 2015" "" ""
.
.SH "NAME"
\fBiconv\fR \- 文件内容编码转换
.
.SH "总览"
\fBiconv [选项\.\.\.] [文件\.\.\.]\fR
.
.SH "描述"
iconv程序把文本从一种编码转换为另一种编码。它把"\-f"选项指定的编码转换为 "\-t"选项指定的编码。这两种编码默认都是当前locale的编码，所有文件都依次进 行转换。默认输出到标准输出设备,亦可指定输出文件。
.
.P
允许的编码与具体系统有关。"\-l"选项可以列出已知的字符集，具体实现可以查看 iconv_open(3)手册页。
.
.P
下面这个例子将从input文件读取内容，并将输出的output文件字符编码从ISO 8859\-15转换到UTF\-8
.
.P
$ iconv \-f ISO\-8859\-15 \-t UTF\-8 < input\.txt > output\.txt
.
.SH "选项"
输入/输出格式规范:
.
.TP
\fB\-f, \-\-from\-code=名称\fR
原始文本编码
.
.TP
\fB\-t, \-\-to\-code=名称\fR
输出文本编码
.
.P
信息:
.
.TP
\fB\-l, \-\-list\fR
列举所有已知的字符集
.
.P
输出控制:
.
.TP
\fB\-c\fR
从输出中忽略无效的字符
.
.TP
\fB\-o, \-\-output=FILE\fR
输出文件
.
.TP
\fB\-s, \-\-silent\fR
关闭警告
.
.TP
\fB\-\-verbose\fR
打印进度信息
.
.TP
\fB\-?, \-\-help\fR
给出该系统求助列表
.
.TP
\fB\-\-usage\fR
给出简要的用法信息
.
.TP
\fB\-V, \-\-version\fR
打印程序版本号
.
.SH "EXIT STATUS"
Zero on success, non\-zero on errors\.
.
.SH "FILES"
/usr/lib/gconv
.
.IP "" 4
.
.nf

  Usual default gconv module path\.
.
.fi
.
.IP "" 0
.
.P
/usr/lib/gconv/gconv\-modules
.
.IP "" 4
.
.nf

  Usual system default gconv module configuration file\.
.
.fi
.
.IP "" 0
.
.P
/usr/lib/gconv/gconv\-modules\.cache
.
.IP "" 4
.
.nf

Usual system gconv module configuration cache\.
.
.fi
.
.IP "" 0
.
.SH "参见(SEEALSO)"
iconv_open(3),locale(7)
.
.SH "版权"
本文档引用了下面网页的文档
.
.P
\fIhttp://niyunjiu\.iteye\.com/blog/739224\fR
