.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "LESS" "1" "March 2015" "" ""
.
.SH "NAME"
\fBless\fR \- opposite to more
.
.SH "总览"
\fBless [参数] 文件\fR
.
.SH "描述"
less 与 more 类似，但使用 less 可以随意浏览文件，而 more 仅能向前移动， 却不能向后移动，而且 less 在查看之前不会加载整个文件。
.
.SH "选项"
.
.TP
\fB\-b <缓冲区大小>\fR
设置缓冲区的大小
.
.TP
\fB\-e\fR
当文件显示结束后，自动离开
.
.TP
\fB\-f\fR
强迫打开特殊文件，例如外围设备代号、目录和二进制文件
.
.TP
\fB\-g\fR
只标志最后搜索的关键词
.
.TP
\fB\-i\fR
忽略搜索时的大小写
.
.TP
\fB\-m\fR
显示类似more命令的百分比
.
.TP
\fB\-N\fR
显示每行的行号
.
.TP
\fB\-o <文件名>\fR
将less 输出的内容在指定文件中保存起来
.
.TP
\fB\-Q\fR
不使用警告音
.
.TP
\fB\-s\fR
显示连续空行为一行
.
.TP
\fB\-S\fR
行过长时间将超出部分舍弃
.
.TP
\fB\-x <数字>\fR
将“tab”键显示为规定的数字空格
.
.SH "命令"
搜索
.
.P
当使用命令"less file\-name"打开一个文件后，可以使用下面的方式在文件中搜 索。搜索时整个文本中匹配的部分会被高亮显示。
.
.IP "1." 4
向前搜索
.
.IP
/ : 使用一个模式进行搜索，并定位到下一个匹配的文本
.
.IP
n : 向前查找下一个匹配的文本
.
.IP
N : 向后查找前一个匹配的文本
.
.IP "2." 4
向后搜索
.
.IP
? : 使用模式进行搜索，并定位到前一个匹配的文本
.
.IP
n : 向后查找下一个匹配的文本
.
.IP
N : 向前查找前一个匹配的文本
.
.IP "3." 4
全屏导航
.
.IP
ctrl + F :向前移动一屏
.
.IP
ctrl + B :向后移动一屏
.
.IP
ctrl + D :向前移动半屏
.
.IP
ctrl + U :向后移动半屏
.
.IP "4." 4
单行导航
.
.IP
j : 向下移动一行
.
.IP
k : 向上移动一行
.
.IP "5." 4
其它导航
.
.IP
G : 移动到最后一行
.
.IP
g : 移动到第一行
.
.IP
按空格:向下翻一页
.
.IP
b:向上翻一页
.
.IP
d:向下翻半页
.
.IP
u:向上翻半页
.
.IP
q / ZZ : 退出 less 命令
.
.IP "6." 4
编辑文件
.
.IP
v : 进入编辑模式，使用配置的编辑器编辑当前文件
.
.IP "7." 4
标记导航
.
.IP "" 0
.
.P
当使用 less 查看大文件时，可以在任何一个位置作标记，可以通过命令导航到 标有特定标记的文本位置。
.
.IP "" 4
.
.nf

ma : 使用 a 标记文本的当前位置

\'a : 导航到标记 a 处
.
.fi
.
.IP "" 0
.
.IP "1." 4
浏览多个文件
.
.IP "" 0
.
.P
方式一，传递多个参数给 less，就能浏览多个文件。
.
.IP "" 4
.
.nf

less file1 file2
.
.fi
.
.IP "" 0
.
.P
方式二，正在浏览一个文件时，使用 :e 打开另一个文件。
.
.IP "" 4
.
.nf

less file1

:e file2
.
.fi
.
.IP "" 0
.
.P
当打开多个文件时，使用如下命令在多个文件之间切换
.
.IP "" 4
.
.nf

:n \- 浏览下一个文件

:p \- 浏览前一个文件
.
.fi
.
.IP "" 0
.
.IP "1." 4
less 版 tail \-f
.
.IP "" 0
.
.P
在 Linux 动态查看日志文件常用的命令非 tail \-f 莫属，其实 less 也能完成 这项工作，使用 F 命令。
.
.SH "实例"
实例1:查看文件
.
.IP "" 4
.
.nf

less log2013\.log
.
.fi
.
.IP "" 0
.
.P
实例2:ps查看进程信息并通过less分页显示
.
.IP "" 4
.
.nf

ps \-ef |less
.
.fi
.
.IP "" 0
.
.P
实例3:查看命令历史使用记录并通过less分页显示
.
.IP "" 4
.
.nf

history | less
.
.fi
.
.IP "" 0
.
.P
实例5:浏览多个文件
.
.IP "" 4
.
.nf

Less log2013\.log log2014\.log
输入 :n后，切换到 log2014\.log
输入 :p 后，切换到log2013\.log
.
.fi
.
.IP "" 0
.
.SH "版权"
本文档由以下文档整理而来
.
.P
\fIhttp://www\.cnblogs\.com/peida/archive/2012/11/05/2754477\.html\fR
.
.P
\fIhttp://blog\.csdn\.net/caihaijiang/article/details/6113419\fR
