.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "LS" "1" "February 2015" "" ""
.
.SH "NAME"
\fBls\fR \- 列出目录内容
.
.SH "提要"
ls [−ikqrs] [−glno] [−A|−a] [−C|−m|−x|−1] [−F|−p] [−H|−L] [−R|−d] [−S|−f|−t] [−c|−u] [文件名\.\.\.]
.
.SH "描述"
ls先列出非目录的文件项，然后是每一个目录中的\fB可显示\fR文件。如果文件名部分 为空，缺省为\fB\.\fR（当前目录）。选项\fB\-d\fR使得目录与非目录项同样对待。除非选 项\fB\-\fR出现，文件名以\fB\.\fR开始的文件不属\fB可显示\fR文件。以当前目录为准，每一组 文件（包括文件和内含文件的目录）分别按文件名排序。如果选项“\-l”存在，每组 文件前显示一摘要行:给出该组文件长度之和（以512字节为单位）。输出是到标准 输出。除非以“\-C”选项要求按多列输出，输出将是一行一个。然而，输出到终端时 ，单列输出或多列输出是不确定的。可以分别用选项“\-1”或“\-C”来强制按单列或多 列输出。
.
.P
dir(也被安装为命令d)等同于\fBls\-C\fR，即文件缺省是多列输出，纵向排序。
.
.P
vdir(也被安装为命令v)等同于\fBls\-l\fR，即文件缺省是按长格式输出。
.
.SH "选项"
.
.TP
\fB\-1,\-\-format=single\-column\fR
一行输出一个文件。
.
.TP
\fB\-a,\-\-all\fR
列出目录中所有文件，包括以“\.”开头的文件。
.
.TP
\fB\-b,\-\-escape\fR
把文件名中不可输出的字符用反斜杠加字符编号的形式列出。
.
.TP
\fB\-c,\-\-time=ctime,\-\-time=status\fR
按状态改变时间排序并输出
.
.P
长格式输出下，按状态改变时间排序并输出目录内容，取代文件修改时间。文件状 态改变，既包括文件被修改，又包括文件属性的变化。
.
.TP
\fB\-d,\-\-directory\fR
将目录名象文件一样列出，而不是列出它们的内容。
.
.TP
\fB\-f\fR
不排序目录内容，按它们在磁盘上存储的顺序列出。同时启动“\-a”选项， 如果在“\-f”之前存在“\-l”、“\-\-color”或“\-s”，则禁止它们。
.
.TP
\fB\-i,\-\-inode\fR
在每个文件左边打印i节点号（也叫文件序列号和索引号）。i节 点号在每个特定的文件系统中是唯一的。
.
.TP
\fB\-l,\-\-format=long,\-\-format=verbose\fR
长格式输出。
.
.P
除每个文件名外，增加显示文件类型、权限、硬链接数、所有者名、组名、大小、 及时间信息（如未指明是其它时间即指修改时间）。对于6个月以上的文件或超出 未来1小时的文件，时间信息中的时分将被年代取代。每个目录列出前，有一行“总 块数”显示目录下全部文件所占的磁盘空间。块默认是1024字节。每一个硬链接都 计入总块数，因此可能重复计数。
.
.TP
\fB\-m,\-\-format=commas\fR
水平列出文件，用逗号和一个空格分隔。
.
.TP
\fB\-n,\-\-numeric\-uid\-gid\fR
列出数字化的UID和GID而不是用户名和组名。
.
.TP
\fB\-o\fR
以长格式列出目录内容，但是不显示组信息。
.
.TP
\fB\-p\fR
在每个文件名后附上一个字符以说明该文件的类型。
.
.P
类似“\-F”选项但是不标示可执行文件。
.
.TP
\fB\-q,\-\-hide\-control\-chars\fR
用问号代替文件名中非打印的字符。缺省选项。
.
.TP
\fB\-r,\-\-reverse\fR
逆序排列目录内容。
.
.TP
\fB\-s,\-\-size\fR
在每个文件名左侧输出该文件占用的空间大小。
.
.TP
\fB\-t,\-\-sort=time\fR
按文件最近修改时间排序，新文件靠前。
.
.TP
\fB\-u,\-\-time=atime,\-\-time=access,\-\-time=use\fR
按文件最近修改时间排序，新文件靠前。
.
.P
类似选项“\-t”，但是用文件最近访问时间取代文件修改时间。如果使用长格式列出 ，打印的时间是最近访问时间。
.
.TP
\fB\-w,\-\-widthcols\fR
设置屏幕宽度列数。
.
.P
默认情况下缺省值先尝试取自终端驱动，否则尝试取自环境变量COLUMNS，都没有 则取80。
.
.TP
\fB\-x,\-\-format=across,\-\-format=horizontal\fR
多列输出，横向排序。
.
.TP
\fB\-A,\-\-almost\-all\fR
显示除\fB\.\fR和\fB\.\.\fR外的所有文件。
.
.TP
\fB\-B,\-\-ignore\-backups\fR
不输出以“~”结尾的备份文件，除非已经在命令行中给出。
.
.TP
\fB\-C,\-\-format=vertical\fR
多列输出，纵向排序。
.
.P
当标准输出是终端时这是缺省项。使用命令名dir和d时，则总是缺省的。
.
.TP
\fB\-F,\-\-classify,\-\-file\-type\fR:

.
.P
在每个文件名后附上一个字符以说明该文件的类型。\fB*\fR表示普通的可执行文件， \fB/\fR表示目录，\fB@\fR表示符号链接，\fB|\fR表示FIFOs，\fB=\fR表示套接字，什么也没有则 表示普通文件。
.
.TP
\fB\-G,\-\-no\-group\fR
以长格式列目录时不显示组信息。
.
.TP
\fBI,\-\-ignorepattern\fR:

.
.P
除非在命令行中给定，不要列出匹配shell文件名匹配式的文件。在shell中，文件 名以\fB\.\fR起始的不与在文件名匹配式开头的通配符匹配。
.
.TP
\fB\-L,\-\-dereference\fR
列出符号链接指向的文件的信息，而不是符号链接本身。
.
.TP
\fB\-Q,\-\-quote\-name\fR
用双引号引起文件名，非打印字符以C语言的方法表示。
.
.TP
\fB\-R,\-\-recursive\fR
递归列出全部目录的内容。
.
.TP
\fB\-S,\-\-sort=size\fR
按文件大小排序，大文件靠前。
.
.TP
\fB\-T,\-\-tabsizecols\fR
设置制表符宽度，缺省为8。为0，则不使用制表符。
.
.TP
\fB\-U,\-\-sort=none\fR:

.
.P
不排序目录内容，按它们在磁盘上存储的顺序列出。选项\fB\-U\fR和\fB\-f\fR的不同是前 者不启动或禁止相关的选项，这在列很大的目录时特别有用，因为不加排序能显著 的加快速度。
.
.TP
\fB\-X,\-\-sort=extension\fR
按文件扩展名的字典序排序。没有扩展名的先列出。
.
.TP
\fB\-\-color[=when]\fR
指定是否使用颜色区别文件类别。
.
.P
由环境变量LS_COLORS指定，见dircolors(1)。when可以被省略，或是以下几项之 一：\fBnone\fR不使用颜色，这是缺省项。\fBauto\fR仅当标准输出是终端时使用。 \fBalways\fR总是使用颜色。指定\fB\-\-color\fR且省略when时等同于\fB\-\-color=always\fR。
.
.TP
\fB\-\-full\-time\fR:

.
.P
列出完整的时间，而不是使用标准的缩写。格式同date(1)的缺省格式。
.
.SH "GNU标准选项"
\-\-help
.
.P
打印用法信息到标准输出并顺利退出。
.
.P
\-\-version
.
.P
打印版本信息到标准输出并顺利退出。
.
.SH "链接"
由CMPP计划的ls(1)整理而来。
