.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "LS" "1" "March 2015" "" ""
.
.SH "NAME"
\fBls\fR \- 列出目录内容
.
.SH "提要"
\fBls [选项\.\.\.] [目录名\.\.\.]\fR
.
.SH "描述"
缺省ls打印出当前目录的文件及文件夹清单\.默认不显示文件名以"\."开始的文件\. 除非指定"−cftuvSUX"或"\-\-sort",否则显示将按文件名的字母顺序排序\.
.
.P
dir(也被安装为命令d)等同于"\fBls \-C\fR",即文件缺省是多列输出,纵向排序\.
.
.P
vdir(也被安装为命令v)等同于"\fBls \-l\fR",即文件缺省是按长格式输出\.
.
.SH "选项"
.
.TP
\fB\-1,\-\-format=single\-column\fR
一行输出一个文件\.
.
.TP
\fB\-a,\-\-all\fR
列出目录中所有文件,包括以"\."开头的文件\.
.
.TP
\fB\-b,\-\-escape\fR
把文件名中不可输出的字符用反斜杠加字符编号的形式列出\.
.
.TP
\fB\-c,\-\-time=ctime,\-\-time=status\fR
按状态改变时间排序并输出,文件状态改变,包括文件的修改,和文件属性 的变化\.
.
.TP
\fB\-d, \-\-directory\fR
列出指定文件夹的目录名,当前目录名为"\."\.
.
.TP
\fB\-f\fR
不排序目录内容,按它们在磁盘上存储的顺序列出\.同时启动"\-aU"选项,禁 用"\-ls"或"\-\-color"选项\.
.
.TP
\fB\-i,\-\-inode\fR
输出i节点号(也叫文件序列号和索引号)\.
.
.TP
\fB\-l,\-\-format=long,\-\-format=verbose\fR
长格式输出\.除每个文件名外,增加显示文件类型、权限、硬链接数、所有 者名、组名、大小、及时间信息(如未指明是其它时间即指修改时间)\.对 于6个月以上的文件或超出未来1小时的文件,时间信息中的时分将被年代 取代\.每个目录列出前,有一行"总块数"显示目录下全部文件所占的磁盘空 间\.块默认是1024字节\.每一个硬链接都计入总块数,因此可能重复计数\.
.
.TP
\fB\-m,\-\-format=commas\fR
水平列出文件,用逗号和一个空格分隔\.
.
.TP
\fB\-n,\-\-numeric\-uid\-gid\fR
列出数字化的UID和GID而不是用户名和组名\.
.
.TP
\fB\-o\fR
以长格式列出目录内容,但是不显示组信息\.
.
.TP
\fB\-p\fR
在每个文件名后附上一个字符以说明该文件的类型\.类似"\-F"选项但是不 标示可执行文件\.
.
.TP
\fB\-q,\-\-hide\-control\-chars\fR
用问号代替文件名中非打印的字符\.缺省选项\.
.
.TP
\fB\-r,\-\-reverse\fR
逆序排列目录内容\.
.
.TP
\fB\-s,\-\-size\fR
在每个文件名左侧输出该文件占用的空间大小\.
.
.TP
\fB\-t,\-\-sort=time\fR
按文件最近修改时间排序,新文件靠前\.
.
.TP
\fB\-u,\-\-time=atime,\-\-time=access,\-\-time=use\fR
按文件最近修改时间排序,新文件靠前\.类似选项"\-t",但是用文件最近访 问时间取代文件修改时间\.如果使用长格式列出,打印的时间是最近访问时 间\.
.
.TP
\fB\-w,\-\-widthcols\fR
设置屏幕宽度列数\.默认情况下缺省值先尝试取自终端驱动,否则尝试取自 环境变量COLUMNS,都没有则取80\.
.
.TP
\fB\-x,\-\-format=across,\-\-format=horizontal\fR
多列输出,横向排序\.
.
.TP
\fB\-A,\-\-almost\-all\fR
显示除\fB\.\fR和\fB\.\.\fR外的所有文件\.
.
.TP
\fB\-B,\-\-ignore\-backups\fR
不输出以"~"结尾的备份文件\.
.
.TP
\fB\-C,\-\-format=vertical\fR
多列输出,纵向排序\.为标准输出是终端时的缺省项\.使用命令dir和d时,则 总是缺省的\.
.
.TP
\fB\-F,\-\-classify,\-\-file\-type\fR
在每个文件名后附上一个字符以说明该文件的类型\.\fB*\fR表示普通的可执行 文件,"/"表示目录,"@"表示符号链接,"|"表示FIFOs,"="表示套接字,什么 也没有则表示普通文件\.
.
.TP
\fB\-G,\-\-no\-group\fR
以长格式列目录时不显示组信息\.
.
.TP
\fBI, \-\-ignorepattern\fR
忽略shell表达式\.
.
.TP
\fB\-L,\-\-dereference\fR
列出符号链接指向的文件的信息,而不是符号链接本身\.
.
.TP
\fB\-Q,\-\-quote\-name\fR
用双引号引起文件名,非打印字符以C语言的方法表示\.
.
.TP
\fB\-R,\-\-recursive\fR
递归列出全部目录的内容\.
.
.TP
\fB\-S,\-\-sort=size\fR
按文件大小排序,大文件靠前\.
.
.TP
\fB\-T,\-\-tabsizecols\fR
设置制表符宽度,缺省为8\.为0,则不使用制表符\.
.
.TP
\fB\-U,\-\-sort=none\fR
不排序目录内容,按它们在磁盘上存储的顺序列出\.选项"\-U"和"\-f"的不同 是前者不启动或禁止相关的选项,这在列很大的目录时特别有用,因为不加 排序能显著的加快速度\.
.
.TP
\fB\-X,\-\-sort=extension\fR
按文件扩展名的字典序排序\.没有扩展名的先列出\.
.
.TP
\fB\-\-color[=when]\fR
是否使用颜色区别文件类别\.when可以被省略,或是以下几项之一:"none" 不使用颜色,这是缺省项\."auto"仅当标准输出是终端时使用\."always"总 是使用颜色\.指定"\-\-color"且省略when时等同于"\-\-color=always"\.
.
.TP
\fB\-\-full\-time\fR
列出完整的时间,而不是使用标准的缩写\.格式同date(1)的缺省格式\.
.
.TP
\fB\-\-help\fR
打印用法信息到标准输出并顺利退出\.
.
.TP
\fB\-\-version\fR
打印版本信息到标准输出并顺利退出\.
.
.SH "退出状态"
.
.TP
\fB0\fR
正常运行
.
.TP
\fB1\fR
发生小错误,比如不能访问子目录
.
.TP
\fB2\fR
发生严重错误,比如不能访问命令参数
.
.SH "版权"
由CMPP计划的ls(1)整理而来\.
