.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MUPDF" "1" "March 2015" "" ""
.
.SH "NAME"
\fBmupdf\fR \- portable c 编写的轻量级PDF阅读器
.
.SH "语法"
\fBmupdf [选项] PDF文件\fR
.
.SH "描述"
.
.TP
\fB−p 123\fR
以用户或所有者身份使用密码123打开加密PDF文件
.
.TP
\fB−r 72\fR
更改初始分辨率,以 dpi 为单位,默认分辨率为72dpi\.
.
.TP
\fB−b 8\fR
修改默认抗锯齿等级,从0开始为关闭抗锯齿到8为最佳,默认值为8
.
.TP
\fB−C RRGGBB\fR
设置整页使用十六进制颜色语法着色,默认值为FFFAF0
.
.SH "鼠标操作"
.
.TP
\fB左键点击\fR
打开链接
.
.TP
\fB左键拖拽\fR
移动页面,如果到达底部或顶部则跳转到下一面或上一面\.
.
.TP
\fB右键拖拽\fR
选择该区域的文本,在X11中,选择的文本可以使用鼠标中间键粘帖,或者按 下CTRL+C复制到剪贴板,在Windows下,选择的区域自动保存到剪贴板中\.
.
.TP
\fB滚动滚轮\fR
上下移动页面,但到顶或到底后不跳转页面\.
.
.TP
\fBShift+滚动滚轮\fR
左右移动页面\.
.
.TP
\fBCtrl+滚动滚轮\fR
放大/缩小显示区域\.
.
.SH "快捷键"
.
.TP
\fBL, R\fR
顺时针/逆时针旋转页面
.
.TP
\fBh, j, k, l\fR
向左,下,上,右移动页面
.
.TP
\fB+, −\fR
放大,缩小显示区域
.
.TP
\fBW, H\fR
使窗口以适合页面的宽度或高度展示
.
.TP
\fBw\fR
在窗口显示文件一页
.
.TP
\fBr\fR
刷新文件
.
.TP
\fB\.\fR
翻到下页页首
.
.TP
\fBb\fR
向上翻页,但页面位置不变
.
.TP
\fB空格键\fR
向下翻页,但页面位置不变
.
.TP
\fB,\fR
翻到上页页尾
.
.TP
\fB<, >\fR
一次回退/前进10页
.
.TP
\fBm\fR
在该页面作标记,最多可以对256页作标记\.
.
.TP
\fBt\fR
回到前一个的标记上
.
.TP
\fB[0\-9]m\fR
保存当前页面到[0\-9]寄存器中
.
.TP
\fB[0\-9]t\fR
回到[0\-9]寄存器所在的页面
.
.TP
\fB123g\fR
跳转到123面
.
.TP
\fBg, G\fR
跳转到第一面/最后一面
.
.TP
\fB/, ?\fR
向前/后搜索关键词
.
.TP
\fBn, N\fR
向后/前到下一个搜索结果
.
.TP
\fBf\fR
全屏模式
.
.TP
\fBp\fR
演示模式
.
.TP
\fBc\fR
彩色或灰阶渲染
.
.TP
\fBC\fR
Toggle full\-page color tinting\.
.
.TP
\fBi\fR
正常或反转颜色渲染
.
.TP
\fBq\fR
退出
.
.SH "参考"
mudraw(1), mutool(1)\.
.
.SH "AUTHOR"
MuPDF is Copyright 2006\-2014 Artifex Software, Inc\.
