.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MV" "1" "March 2015" "" ""
.
.SH "NAME"
\fBmv\fR \- 移动和重命名文件
.
.SH "语法"
\fBmv [OPTION]\.\.\. [\-T] SOURCE DEST\fR
.
.P
\fBmv [OPTION]\.\.\. SOURCE\.\.\. DIRECTORY\fR
.
.P
\fBmv [OPTION]\.\.\. \-t DIRECTORY SOURCE\.\.\.\fR
.
.SH "描述"
mv命令来为文件或目录改名或将文件由一个目录移入另一个目录中\.该命令等同于 DOS系统下的ren和move命令的组合\.它的使用权限是所有用户\.
.
.P
"mv 文件 目标文件":该命令对文件重命名,对于目录,则是修改目录名\.此时,文件 只能有一个\.
.
.P
"mv 文件 目录":该命令中文件可以有多个,mv命令将指定的文件均移至目标目录 中\.在跨文件系统移动文件时,mv先拷贝,再将原有文件删除,而链至该文件的链接也 将丢失\.
.
.SH "选项"
.
.TP
\fB\-i\fR
交互方式操作,mv操作将覆盖已存在的同名文件时会询问是否覆盖,并要求 用户回答”y”或”n”,这样可以避免误覆盖文件\.
.
.TP
\fB\-f\fR
禁止交互操作,mv操作覆盖某个已有的目标文件时不会给出任何指示\.
.
.TP
\fB\-n, \-\-no\-clobber\fR
不覆盖已存在的同名文件
.
.P
如果同时给出"\-i","\-f","\-n"选项,那么只有最后的那个选项生效\.
.
.TP
\fB\-\-backup[=CONTROL]\fR
make a backup of each existing destination file
.
.TP
\fB\-b\fR
like \-\-backup but does not accept an argument
.
.TP
\fB\-S, \-\-suffix=SUFFIX\fR
override the usual backup suffix
.
.TP
\fB\-t, \-\-target\-directory=DIRECTORY\fR
move all SOURCE arguments into DIRECTORY
.
.TP
\fB\-T, \-\-no\-target\-directory\fR
treat DEST as a normal file
.
.TP
\fB\-u, \-\-update\fR
move only when the SOURCE file is newer than the destination file or when the destination file is missing
.
.TP
\fB\-v, \-\-verbose\fR
explain what is being done
.
.TP
\fB\-Z, \-\-context\fR
set SELinux security context of destination file to default type
.
.TP
\fB\-\-help\fR
display this help and exit
.
.TP
\fB\-\-version\fR
output version information and exit
.
.SH "参考"
cp(1), ln(1)
.
.SH "版权"

