.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PS" "1" "March 2015" "" ""
.
.SH "NAME"
\fBps\fR \- 显示某个时间点的进程状态
.
.SH "总览"
\fBps [options] [\-\-help]\fR
.
.SH "描述"
ps命令能够给出当前系统中进程的快照\.它能捕获系统在某一事件的进程状态\.如果 你想不断更新查看的这个状态,可以使用top命令\.
.
.P
ps命令支持三种使用的语法格式:
.
.IP "" 4
.
.nf

1\. UNIX风格,选项可以组合在一起,并且选项前必须有“\-”连字符
2\. BSD风格,选项可以组合在一起,但是选项前不能有“\-”连字符
3\. GNU风格的长选项,选项前有两个“\-”连字符\.
.
.fi
.
.IP "" 0
.
.P
我们能够混用这几种风格,但是可能会发生冲突\.
.
.P
linux上进程有5种状态:
.
.IP "" 4
.
.nf

1\. 运行(正在运行或在运行队列中等待)
2\. 中断(休眠中,受阻,在等待某个条件的形成或接受到信号)
3\. 不可中断(收到信号不唤醒和不可运行, 进程必须等待直到有中断发生)
4\. 僵死(进程已终止,但进程描述符存在,直到父进程调用wait4()后释放)
5\. 停止(进程收到SIGSTOP,SIGSTP,SIGTIN,SIGTOU信号后停止运行运行)
.
.fi
.
.IP "" 0
.
.P
ps工具标识进程的5种状态码:
.
.IP "" 4
.
.nf

D 不可中断 uninterruptible sleep (usually IO)
R 运行 runnable (on run queue)
S 中断 sleeping
T 停止 traced or stopped
Z 僵死 a defunct (”zombie”) process
.
.fi
.
.IP "" 0
.
.P
ps的参数非常多,常用的有"\-A"列出所有的进程,"\-w"显示加宽可以显示较多的资讯 ,"\-au"显示较详细的资讯,"\-aux"显示所有包含其他使用者的进程
.
.SH "选项"
.
.TP
\fB\-a\fR
显示所有终端下不与 terminal 有关的所有进程\.
.
.TP
\fBa\fR
显示当前终端下的所有进程,包括其他用户的进程\.
.
.TP
\fB\-A\fR
显示所有进程\.
.
.TP
\fB\-c\fR
显示CLS和PRI栏位\.
.
.TP
\fBc\fR
列出进程时,显示每个进程真正的指令名称,而不包含路径,参数或常驻服 务的标示\.
.
.TP
\fB\-C 指令名称\fR
指定执行指令的名称,并列出该指令的进程的状况\.
.
.TP
\fB\-d\fR
显示所有进程,但不包括阶段作业领导者的进程\.
.
.TP
\fB\-e\fR
此参数的效果和指定"A"参数相同\.
.
.TP
\fBe\fR
列出进程时,显示每个进程所使用的环境变量\.
.
.TP
\fB\-f\fR
显示UID,PPIP,C与STIME栏位\.
.
.TP
\fBf\fR
用ASCII字符显示树状结构,表达进程间的相互关系\.
.
.TP
\fB\-g 群组名称\fR
此参数的效果和指定"\-G"参数相同,当亦能使用阶段作业领导者的名称来 指定\.
.
.TP
\fBg\fR
显示现行终端机下的所有进程,包括群组领导者的进程\.
.
.TP
\fB\-G 群组识别码\fR
列出属于该群组的进程的状况,也可使用群组名称来指定\.
.
.TP
\fBh\fR
不显示标题列\.
.
.TP
\fB\-H\fR
显示树状结构,表示进程间的相互关系\.
.
.TP
\fB\-j 或 j\fR
采用工作控制的格式显示进程状况\.
.
.TP
\fB\-l 或 l\fR
采用详细的格式来显示进程状况\.
.
.TP
\fBL\fR
列出栏位的相关信息\.
.
.TP
\fB\-m 或 m\fR
显示所有的执行绪\.
.
.TP
\fBn\fR
以数字来表示USER和WCHAN栏位\.
.
.TP
\fB\-N\fR
显示所有的进程,除了执行ps指令终端机下的进程之外\.
.
.TP
\fB\-p 进程识别码\fR
指定进程识别码,并列出该进程的状况\.
.
.TP
\fBp 进程识别码\fR
此参数的效果和指定"\-p"参数相同,只在列表格式方面稍有差异\.
.
.TP
\fBr\fR
只列出现行终端机正在执行中的进程\.
.
.TP
\fB\-s 阶段作业\fR
指定阶段作业的进程识别码,并列出隶属该阶段作业的进程的状况\.
.
.TP
\fBs\fR
采用进程信号的格式显示进程状况\.
.
.TP
\fBS\fR
列出进程时,包括已中断的子进程资料\.
.
.TP
\fB\-t 终端机编号\fR
指定终端机编号,并列出属于该终端机的进程的状况\.
.
.TP
\fBt 终端机编号\fR
此参数的效果和指定"\-t"参数相同,只在列表格式方面稍有差异\.
.
.TP
\fB\-T\fR
显示现行终端机下的所有进程\.
.
.TP
\fB\-u 用户识别码\fR
此参数的效果和指定"\-U"参数相同\.
.
.TP
\fBu\fR
以用户为主的格式来显示进程状况\.
.
.TP
\fB\-U 用户识别码\fR
列出属于该用户的进程的状况,也可使用用户名称来指定\.
.
.TP
\fBU 用户名称\fR
列出属于该用户的进程的状况\.
.
.TP
\fBv\fR
采用虚拟内存的格式显示进程状况\.
.
.TP
\fB\-V 或 V\fR
显示版本信息\.
.
.TP
\fB\-w 或 w\fR
采用宽阔的格式来显示进程状况\.
.
.TP
\fBx\fR
显示所有进程,不以终端机来区分\.
.
.TP
\fBX\fR
采用旧式的Linux i386登陆格式显示进程状况\.
.
.TP
\fB\-y\fR
配合参数"\-l"使用时,不显示F(flag)栏位,并以RSS栏位取代ADDR栏位\.
.
.TP
\fB\-进程识别码\fR
此参数的效果和指定"p"参数相同\.
.
.TP
\fB\-\-cols n\fR
设置每列的最大字符数n\.
.
.TP
\fB\-\-columns n\fR
每列字符数 此参数的效果和指定"\-\-cols"参数相同\.
.
.TP
\fB\-\-cumulative\fR
此参数的效果和指定"S"参数相同\.
.
.TP
\fB\-\-deselect\fR
此参数的效果和指定"\-N"参数相同\.
.
.TP
\fB\-\-forest\fR
此参数的效果和指定"f"参数相同\.
.
.TP
\fB\-\-headers\fR
重复显示标题列\.
.
.TP
\fB\-\-help\fR
在线帮助\.
.
.TP
\fB\-\-info\fR
显示排错信息\.
.
.TP
\fB\-\-lines n\fR
显示列数 设置显示画面的列数\.
.
.TP
\fB\-\-no\-headers\fR
此参数的效果和指定"h"参数相同,只在列表格式方面稍有差异\.
.
.TP
\fB\-\-group 群组名称\fR
此参数的效果和指定"\-G"参数相同\.
.
.TP
\fB\-\-Group 群组识别码\fR
此参数的效果和指定"\-G"参数相同\.
.
.TP
\fB\-\-pid 进程识别码\fR
此参数的效果和指定"\-p"参数相同\.
.
.TP
\fB\-\-rows 显示列数\fR
此参数的效果和指定"\-\-lines"参数相同\.
.
.TP
\fB\-\-sid 阶段作业\fR
此参数的效果和指定"\-s"参数相同\.
.
.TP
\fB\-\-tty 终端机编号\fR
此参数的效果和指定"\-t"参数相同\.
.
.TP
\fB\-\-user 用户名称\fR
此参数的效果和指定"\-U"参数相同\.
.
.TP
\fB\-\-User 用户识别码\fR
此参数的效果和指定"\-U"参数相同\.
.
.TP
\fB\-\-version\fR
此参数的效果和指定"\-V"参数相同\.
.
.TP
\fB\-\-widty 每列字符数\fR
此参数的效果和指定"\-cols"参数相同\.
.
.SH "输出格式"
.
.nf

USER: 进程拥有者
PID:  运行命令(CMD)的进程编号
%CPU: 占用的 CPU 使用率
%MEM: 占用的内存使用率
VSZ: 占用的虚拟内存大小
RSS: 占用的内存大小
TTY: 终端的次要装置号码
STAT: 该进程的状态
D: 不可中断的静止
R: 正在执行中
S: 静止状态
T: 暂停执行
Z: 不存在但暂时无法消除
W: 没有足够的内存分页可分配
: 高优先序的进程
N: 低优先序的进程
L: 有内存分页分配并锁在内存内
START: 进程开始时间
TIME: 执行的时间
CMD:所执行的指令
.
.fi
.
.SH "版权"
http://linux\.sheup\.com/linux/4/31133\.html
.
.P
http://blog\.csdn\.net/jsufcz/article/details/5044932
