.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PWD" "1" "February 2015" "" ""
.
.SH "NAME"
\fBpwd\fR \- 显示当前目录或者工作目录
.
.SH "摘要"
\fBpwd [选项]\fR
.
.SH "描述"
打印当前工作目录的完整文件名
.
.TP
\fB\-L,\-\-logical\fR
显示环境变量PWD的值，甚至它包含符号链接
.
.TP
\fB\-P,\-\-physical\fR
忽略全部的符号链接
.
.TP
\fB\-\-help\fR
显示帮助并退出
.
.TP
\fB\-\-version\fR
输出版本信息并退出
.
.P
你的shell也许有自己版本的pwd命令，他们通常会取代这里描述的版本。请参考你 的shell提供的文档来了解它所支持的选项的细节。
.
.SH "参考"
getcwd(3)
.
.P
pwd的完整文档使用Texinfo手册进行维护。如果info和pwd程序已经正确地安装在 了你的电脑上，通过下述命令
.
.IP "" 4
.
.nf

info coreutils \'pwd invocation\'
.
.fi
.
.IP "" 0
.
.P
可以访问完整的使用手册
