.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RMDIR" "1" "February 2015" "" ""
.
.SH "NAME"
\fBrmdir\fR \- 删除空目录
.
.SH "总览"
\fBrmdir [\-p] dir\.\.\.\fR
.
.SH "描述"
rmdir删除空目录。如果所给出的目录不为空，则报错。
.
.SH "选项"
.
.TP
\fB\-p,\-\-parents\fR
如果目录由多个路径组成，从最后一个路径开始依次删除，直到所有的路 径都被删完。命令"\fBrmdir \-p a/b/c\fR"按照"\fBrmdir /a/b/c; rmdir a/b; rmdir a\fR"的顺序删除目录
.
.TP
\fB\-\-ignore\-fail\-on\-non\-empty\fR
通常，rmdir拒绝删除非空目录。这个选项将使命令忽略非空目录而进行 删除操作。
.
.TP
\fB\-\-help\fR
在标准输出上显示使用信息并顺利退出
.
.TP
\fB\-\-version\fR
在标准输出上显示版本信息并顺利退出
.
.SH "EXAMPLES"
命令\fBrmdir foo\fR将删除空目录foo。要删除一个非空目录，并且包括其下属所有内 容，可以使用命令\'rm \-r foo\'。
