.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UNAME" "1" "February 2015" "" ""
.
.SH "NAME"
\fBuname\fR \- 显示系统信息
.
.SH "描述"
显示相应的系统信息。没有指定选项时，同\fB\-s\fR。
.
.SH "选项"
\fBuname [−amnrsv]\fR
.
.TP
\fB\-a,\-\-all\fR
显示所有的信息
.
.TP
\fB\-m,\-\-machine\fR
显示机器(硬件)类型
.
.TP
\fB\-n,\-\-nodename\fR
显示机器的网络节点主机名
.
.TP
\fB\-r,\-\-release\fR
显示操作系统发行版本
.
.TP
\fB\-s,\-\-sysname\fR
显示操作系统名
.
.TP
\fB\-p,\-\-processor\fR
显示主机处理器(CPU)类型
.
.TP
\fB\-v\fR
显示操作系统版本
.
.TP
\fB\-\-help\fR
显示本帮助并退出
.
.TP
\fB\-\-version\fR
显示版本信息并退出

