.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UNZIP" "1" "March 2015" "" ""
.
.SH "NAME"
\fBunzip\fR \- 处理zip文件
.
.SH "语法"
\fBunzip 选项\.\.\. 压缩文件\.\.\.\fR
.
.SH "描述"
unzip可以列出zip压缩文档的内容,测试该文档的完整度和解压\.没有选项时,默认 操作是将文档解压到当前文件夹,并保留文件结构\.
.
.SH "选项"
.
.TP
\fB\-c\fR
将解压缩的结果显示到屏幕上,并对字符做适当的转换\.
.
.TP
\fB\-f\fR
更新现有的文件\.
.
.TP
\fB\-l\fR
显示压缩文件内所包含的文件\.
.
.TP
\fB\-p\fR
与"\-c"参数类似,会将解压缩的结果显示到屏幕上,但不会执行任何的转 换\.
.
.TP
\fB\-t\fR
检查压缩文件是否正确,但不解压\.
.
.TP
\fB\-u\fR
与"\-f"参数类似,但是除了更新现有的文件外,也会将压缩文件中的其他 文件解压缩到目录中\.
.
.TP
\fB\-v\fR
执行是时显示详细的信息\.或查看压缩文件目录,但不解压\.
.
.TP
\fB\-z\fR
仅显示压缩文件的备注文字\.
.
.TP
\fB\-a\fR
对文本文件进行必要的字符转换\.
.
.TP
\fB\-b\fR
不要对文本文件进行字符转换\.
.
.TP
\fB\-C\fR
压缩文件中的文件名称区分大小写\.
.
.TP
\fB\-d dir\fR
把压缩文件解压到dir目录下\.
.
.TP
\fB\-j\fR
不重建文档的目录结构,把所有文件解压到同一目录下\.
.
.TP
\fB\-L\fR
将压缩文件中的全部文件名改为小写\.
.
.TP
\fB\-M\fR
将输出结果送到more程序处理\.
.
.TP
\fB\-n\fR
解压缩时不覆盖原有的文件\.
.
.TP
\fB\-o\fR
覆盖已存在的文件且不要求用户确认\.
.
.TP
\fB\-P password\fR
解压时使用密码
.
.TP
\fB\-q\fR
执行时不显示任何信息\.
.
.TP
\fB\-s\fR
将文件名中的空白字符转换为底线字符\.
.
.TP
\fB\-t\fR
测试文件有无损坏,但不解压\.
.
.TP
\fB\-v\fR
查看压缩文件目录,但不解压\.
.
.TP
\fB\-V\fR
保留VMS的文件版本信息\.
.
.TP
\fB\-x files\fR
解压时指定不要处理的文件\.
.
.TP
\fB\-X\fR
解压缩时同时回存文件原来的UID/GID\.
.
.TP
\fB\-z\fR
只显示压缩文件的注解\.
.
.TP
\fB\-Z\fR
等于执行zipinfo指令\.

