.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WC" "1" "February 2015" "" ""
.
.SH "NAME"
\fBwc\fR \- 显示文件的行数、词数和字节数
.
.SH "摘要"
\fBwc [−c|−m] [−lw] [file\.\.\.]\fR
.
.SH "描述"
显示文件的行数、词数和字节数，和一个统计行（若有多个文件被指定）。当没有 文件或者文件为空的时候，读取标准输入。一个单词是指非零长度有序的通过空格 限制长度的字符组。下列选项习惯用于选择那一个统计数被显示，总共有这些选项 ：行数、词数、字符数、字节数。
.
.SH "选项"
.
.TP
\fB−c,−−bytes\fR
显示字节数
.
.TP
\fB−m,−−chars\fR
显示字符数
.
.TP
\fB−l,−−lines\fR
显示行数
.
.TP
\fB−w,−−words\fR
显示词数
.
.P
wc的完整文档使用Texinfo手册进行维护。如果info和wc程序已经正确地安装在了 你的电脑上，通过下述命令
.
.P
info coreutils \'wc invocation\'
.
.P
可以访问完整的使用手册
.
.SH "版权"
由LCTT \fIhttp://lctt\.github\.io/\fR项目wc(1)整理而来。
