.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WHEREIS" "1" "March 2015" "" ""
.
.SH "NAME"
\fBwhereis\fR \- 定位可执行文件,源代码,帮助文件的位置
.
.SH "综述"
\fBwhereis [\-bfmsu] [\-BMS 目录\.\.\.][文件\.\.\.]\fR
.
.SH "描述"
whereis指令会在特定目录中查找符合条件的文件,这些文件应属于原始代码,二进 制文件,或是帮助文件,whereis then attempts to locate the desired program in the standard Linux places, and in the places specified by $PATH and $MANPATH\.
.
.SH "选项"
.
.TP
\fB\-b\fR
只查找二进制文件\.
.
.TP
\fB\-B DIR\fR
只在设置的目录DIR下查找二进制文件\.
.
.TP
\fB\-f\fR
不显示文件名前的路径名称\.
.
.TP
\fB\-m\fR
只查找说明文件\.
.
.TP
\fB\-M DIR\fR
只在设置的目录DIR下查找说明文件\.
.
.TP
\fB\-s\fR
只查找原始代码文件\.
.
.TP
\fB\-S DIR\fR
只在设置的目录DIR下查找原始代码文件\.
.
.TP
\fB\-u\fR
查找不包含指定类型的文件\.

