.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ZIP" "1" "March 2015" "" ""
.
.SH "NAME"
\fBzip\fR \- 压缩文件
.
.SH "语法"
\fBzip [参数] [打包后的文件名] [打包的目录路径]\fR
.
.SH "描述"
ZIP文件格式是一种流行的数据压缩和文档储存的文件格式,原名Deflate\.ZIP通常 使用后缀名“\.zip”,它的MIME格式为application/zip\.目前,ZIP格式属于几种主流 的压缩格式之一,其竞争者包括RAR格式以及开放源码的7z格式\.从性能上比较,RAR 及7z格式较ZIP格式压缩率较高,而7\-Zip由于提供了免费的压缩工具而逐渐在更多 的领域得到应用\.Microsoft从Windows ME操作系统开始内置对zip格式的支持,即 使用户的电脑上没有安装解压缩软件,也能打开和制作zip格式的压缩文件,OS X和 流行的Linux操作系统也对zip格式提供了类似的支持\.因此如果在网络上传播和分 发文件,zip格式往往是最常用的选择\.(摘自Wikipedia)
.
.SH "选项"
.
.TP
\fB\-a\fR
将文件转成ASCII模式
.
.TP
\fB\-A\fR
调整可执行的自动解压缩文件
.
.TP
\fB\-b path\fR
指定暂时存放文件的目录path\.
.
.TP
\fB\-c\fR
替每个被压缩的文件加上注释\.
.
.TP
\fB\-d\fR
从压缩文件内删除指定的文件\.
.
.TP
\fB\-D\fR
压缩文件内不建立目录名称\.
.
.TP
\fB\-f\fR
此参数的效果和指定"\-u"参数类似,但不仅更新既有文件,如果某些文件原 本不存在于压缩文件内,使用本参数会一并将其加入压缩文件中\.
.
.TP
\fB\-F\fR
尝试修复已损坏的压缩文件\.
.
.TP
\fB\-g\fR
将文件压缩后附加在既有的压缩文件之后,而非另行建立新的压缩文件\.
.
.TP
\fB\-h\fR
在线帮助\.
.
.TP
\fB\-i files\fR
只压缩特定的文件files,可以使用shell通配符,比如"*\.c"表示所有的 以"\.c"结尾的文件\.
.
.TP
\fB\-j\fR
压缩时只保存文件,而不保存其下的目录结构\.
.
.TP
\fB\-J\fR
删除压缩文件前面不必要的数据\.
.
.TP
\fB\-k\fR
使用MS\-DOS兼容格式的文件名称\.
.
.TP
\fB\-l\fR
压缩文件时,把LF字符置换成LF+CR字符\.
.
.TP
\fB\-ll\fR
压缩文件时,把LF+CR字符置换成LF字符\.
.
.TP
\fB\-L\fR
显示版权信息\.
.
.TP
\fB\-m\fR
将文件压缩并加入压缩文件后,删除原始文件,即把文件移到压缩文件中\.
.
.TP
\fB\-n suffixes\fR
不压缩具有特定字尾字符串suffixes的文件,即这些文件仅被放于压缩文 件中,而不被压缩\.不同suffixes由冒号或分号隔开,默认情况下,zip不压 缩如下以如下字尾字符串结尾的文件:"\.Z:\.zip:\.zoo:\.arc:\.lzh:\.arj", 环境变量ZIPOPT可以用来改变该默认选项\.如果希望压缩所有的文件可以 使用"\-n :","\-9"选项也试图压缩所有类型的文件\.
.
.TP
\fB\-o\fR
以压缩文件内拥有最新更改时间的文件为准,将压缩文件的更改时间设成 和该文件相同\.
.
.TP
\fB−P password, −−password password\fR
使用密码password加密文件\.
.
.TP
\fB\-q\fR
不显示指令执行过程\.
.
.TP
\fB\-r\fR
递归处理,将指定目录下的所有文件和子目录一并处理\.
.
.TP
\fB\-S\fR
包含系统和隐藏文件\.
.
.TP
\fB−t mmddyyyy\fR
把压缩文件的日期设成指定的日期,格式类似于"02191990",表示1990年2 月19号\.
.
.TP
\fB\-T\fR
检查备份文件内的每个文件是否正确无误\.
.
.TP
\fB\-u\fR
更换较新的文件到压缩文件内\.
.
.TP
\fB\-v\fR
显示指令执行过程或显示版本信息\.
.
.TP
\fB\-V\fR
保存VMS操作系统的文件属性\.
.
.TP
\fB\-w\fR
在文件名称里假如版本编号,本参数仅在VMS操作系统下有效\.
.
.TP
\fB\-x files\fR
类似于"\-i"选项,表示压缩时排除特定的文件\.
.
.TP
\fB\-X\fR
不保存额外的文件属性\.
.
.TP
\fB\-y\fR
直接保存符号连接,而非该连接所指向的文件,本参数仅在UNIX之类的系统 下有效\.
.
.TP
\fB\-z\fR
替压缩文件加上注释\.
.
.TP
\fB\-$\fR
保存第一个被压缩文件所在磁盘的卷册名称\.
.
.TP
\fB\-N\fR
设定压缩率,压缩率N为0到9之间的整数,"\-0"表示不压缩,"\-1"表示最快速 度压缩,"\-9"表示最大压缩率,但压缩速度也最慢\.默认为"\-6"\.

