.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "VMSTAT" "8" "March 2015" "" ""
.
.SH "NAME"
\fBvmstat\fR \- − 报告虚拟内存的统计信息
.
.SH "总览"
\fBvmstat [options] [延时 [次数]]\fR
.
.SH "描述"
vmstat对系统的进程情况、内存使用情况、交换页和I/O块使用情况、中断以及CPU 使用情况进行统计并报告相应的信息\.
.
.P
vmstat输出的第一个显示内容指出了计算机自上次重启至今的平均使用情况\.后面 的每一行信息是按延时定期地显示系统的各部分信息\.进程信息和内存信息都是即 时产生的\.
.
.SH "选项"
.
.TP
\fB\-V\fR
显示版本
.
.TP
\fB\-n\fR
只在开始时显示一次各字段名称
.
.TP
\fB\-a\fR
显示活跃和非活跃内存
.
.TP
\fB\-d\fR
显示磁盘相关统计信息
.
.TP
\fB\-D\fR
以表格的形式显示磁盘信息
.
.TP
\fB\-p\fR
显示指定磁盘分区相关信息
.
.TP
\fB\-s\fR
显示内存相关统计信息及多种活动数量
.
.TP
\fB\-m\fR
显示slabinfo
.
.TP
\fB\-t\fR
显示统计信息的同时打印出时间,该参数和上面的参数同时使用
.
.TP
\fB\-S\fR
指定单位显示,如,k,K,m,M
.
.TP
\fB\-n\fR
令第一次的信息只显示一次而不是周期地产生\.
.
.P
延时是以秒为单位的刷新时间间隔\.如果没有给出此延时时间,则仅显示系统启动至 今的平均值\.
.
.P
次数指的是更新的次数\.如果没有指定此数而又定义了延时时间,则次数的默认值是 无穷次\.
.
.SH "输出信息"
\fBProcs\fR
.
.P
procs有r列和b列\.r列代表等待访问CPU进程的数量\.而b列意味着睡眠进程的数量\. 在这些列的下面,是它们的值\.
.
.IP "" 4
.
.nf

Procs
r:等待运行的进程数
b:处在非中断睡眠状态的进程数
w:被交换出去的可运行的进程数\.
.
.fi
.
.IP "" 0
.
.P
\fBMemory\fR
.
.P
memory有swpd,free,buff和cache列等\.这些信息和命令"free \-m"相同\.swpd列显 示了有多少内存已经被交换到了交换文件或者磁盘\.free列显示了未分配的可用内 存\.buff列显示了使用中的内存\.cache列显示了有多少内存可以被交换到交换文件 或者磁盘上如果一些应用需要他们\.
.
.IP "" 4
.
.nf

Memory
swpd:虚拟内存使用情况,单位：KB
free:空闲的内存,单位KB
buff:被用来做为缓存的内存数,单位：KB
cache: the amount of memory used as cache\.
inact: the amount of inactive memory\.  (\-a option)
active: the amount of active memory\.  (\-a option)
.
.fi
.
.IP "" 0
.
.P
\fBSwap\fR
.
.P
swap显示了从交换系统上发送或取回了多少内存\.si列告诉我们每秒有多少内存被 从swap移到真实内存中(In)\.so列告诉我们每秒有多少内存被从真实内存移到swap 中(Out)\.
.
.IP "" 4
.
.nf

Swap
si:从磁盘交换到内存的交换页数量,单位：KB/秒
so:从内存交换到磁盘的交换页数量,单位：KB/秒
.
.fi
.
.IP "" 0
.
.P
\fBI/O\fR
.
.P
io依据块的读写显示了每秒输入输出的活动\.bi列告诉我们收到的块数量,bo列告诉 我们发送的块数量\.
.
.IP "" 4
.
.nf

IO
bi:发送到块设备的块数,单位：块/秒
bo:从块设备接收到的块数,单位：块/秒
.
.fi
.
.IP "" 0
.
.P
\fBSystem\fR
.
.P
system显示了每秒的系统操作数量\.in列显示了系统每秒被中断的数量\.cs列显示 了系统为了处理所以任务而上下文切换的数量\.
.
.IP "" 4
.
.nf

System
in:每秒的中断数,包括时钟中断
cs:每秒的环境(上下文)切换次数
.
.fi
.
.IP "" 0
.
.P
\fBCPU\fR
.
.P
CPU告诉了我们CPU资源的使用情况\.us列显示了处理器在非内核程序消耗的时间\.sy 列显示了处理器在内核相关任务上消耗的时间\.id列显示了处理器的空闲时间\.wa列 显示了处理器在等待IO操作完成以继续处理任务上的时间\.
.
.IP "" 4
.
.nf

CPU
按CPU的总使用百分比来显示
us:CPU使用时间
sy:CPU系统使用时间
id:闲置时间
.
.fi
.
.IP "" 0
.
.SH "注意"
运行vmstat不须要特别的使用权限\.
.
.P
这些系统信息是用来向用户提供分析系统瓶颈问题信息的\.linux在计算进程情况时 不将正在运行的vmstat自己计算进去\.
.
.P
当前所在的linux块的大小都是1K,而CD\-ROM文件系统的块大小为2K\.
.
.SH "范例"
5秒时间内进行5次采样
.
.IP "" 4
.
.nf

vmstat 5 5
.
.fi
.
.IP "" 0
.
.SH "文件"
/proc/meninfo, /proc/stat, /proc/*/stat
.
.SH "参见"
ps(1), top(1), free(1)
