'\" t
.\"     Title: scp
.\"    Author: Timo Rinne <Mt tri@iki.fi>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2015-01-30
.\"    Manual: 一般命令手册
.\"    Source: manpages_zh
.\"  Language: Chinese Simplified
.\"
.TH "SCP" "1" "2015\-01\-30" "manpages_zh" "一般命令手册"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名称"
scp \- 安全复制 (远程文件复制程序)
.SH "总览 (SYNOPSIS)"
.HP \w'\fBscp\fR\ 'u
\fBscp\fR [\fB\-12346BCpqrv\fR] [\fB\-c\fR\ \fIcipher\fR] [\fB\-F\fR\ \fIssh_config\fR] [\fB\-i\fR\ \fIidentity_file\fR] [\fB\-l\fR\ \fIlimit\fR] [\fB\-o\fR\ \fIssh_option\fR] [\fB\-P\fR\ \fIport\fR] [\fB\-S\fR\ \fIprogram\fR] [[\fIuser\fR@]\fIhost1\fR:]\fIfile1\fR\0\fI\&.\&.\&.\fR [[\fIuser\fR@]\fIhost2\fR:]\fIfile2\fR
.SH "描述 (DESCRIPTION)"
.PP
\fBscp\fR
在网络的主机间复制文件。 它使用
\fBssh\fR(1) 实现数据传输, 使用相同的验证方式, 提供与
\fBssh\fR(1) 同等的安全性。
\fBscp\fR
会在有必要的情况下 向用户询问密码与验证密文 (passphrase) 用来进行身份验证。
.PP
文件名可能包含一个用户名和主机信息, 以此指示文件将被 / 从该主机复制。 本地文件名称可以显式地使用绝对或相对路径名, 以此避免
\fBscp\fR
将含有 `:\*(Aq 字符的文件名字符串当作主机信息处理。 在两台远程主机间进行文件复制同样是被允许的。
.SH "选项 (OPTIONS)"
.PP
可接受的选项如下所示：
.PP
待翻译。
.SH "返回状态 (EXIT STATUS)"
.PP
Ex \-std scp
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fB注意\fR
.ps -1
.br
.PP
译者注：暂不明白以上原文的含义。
.sp .5v
.RE
.SH "参见 (SEE ALSO)"
.PP
\fBsftp\fR(1),
\fBssh\fR(1),
\fBssh\-add\fR(1),
\fBssh\-agent\fR(1),
\fBssh\-keygen\fR(1),
\fBssh_config\fR(1),
\fBsshd\fR(8)
.SH "历史 (HISTORY)"
.PP
\fBscp\fR
is based on the rcp program in Bx source code from the Regents of the University of California\&.
.SH "注记 (NOTES)"
.PP
本文档非正式翻译由 manpages_zh 项目提供。
.PP
请向本项目提交文法错误报告与改进建议：
\m[blue]\fB\%https://github.com/intetnet/manpages_zh\fR\m[]
.SH "作者"
.PP
\fBTimo Rinne\fR <\&Mt tri@iki\&.fi\&>
.RS 4
作者
.RE
.PP
\fBTatu Ylonen\fR <\&Mt ylo@cs\&.hut\&.fi\&>
.RS 4
作者
.RE
.PP
\fBBoyuan Yang\fR <\&073plan@gmail\&.com\&>
.RS 4
翻译本篇文章
.RE
.SH "版权"
.br
版权 \(co 2015 manpages_zh
.br
