imagemagick /usr/share/man/
imagemagick /usr/share/man/man1/
imagemagick /usr/share/man/man1/ImageMagick.1.gz
imagemagick /usr/share/man/man1/Magick++-config.1.gz
imagemagick /usr/share/man/man1/Magick-config.1.gz
imagemagick /usr/share/man/man1/MagickCore-config.1.gz
imagemagick /usr/share/man/man1/MagickWand-config.1.gz
imagemagick /usr/share/man/man1/Wand-config.1.gz
imagemagick /usr/share/man/man1/animate.1.gz
imagemagick /usr/share/man/man1/compare.1.gz
imagemagick /usr/share/man/man1/composite.1.gz
imagemagick /usr/share/man/man1/conjure.1.gz
imagemagick /usr/share/man/man1/convert.1.gz
imagemagick /usr/share/man/man1/display.1.gz
imagemagick /usr/share/man/man1/identify.1.gz
imagemagick /usr/share/man/man1/import.1.gz
imagemagick /usr/share/man/man1/mogrify.1.gz
imagemagick /usr/share/man/man1/montage.1.gz
imagemagick /usr/share/man/man1/stream.1.gz
imagemagick /usr/share/man/man3/
imagemagick /usr/share/man/man3/Image::Magick.3pm.gz
imagemagick /usr/share/man/man3/Image::Magick::Q16HDRI.3pm.gz
