shadow /usr/share/man/
shadow /usr/share/man/cs/
shadow /usr/share/man/cs/man1/
shadow /usr/share/man/cs/man1/expiry.1.gz
shadow /usr/share/man/cs/man1/gpasswd.1.gz
shadow /usr/share/man/cs/man1/groups.1.gz
shadow /usr/share/man/cs/man5/
shadow /usr/share/man/cs/man5/faillog.5.gz
shadow /usr/share/man/cs/man5/gshadow.5.gz
shadow /usr/share/man/cs/man5/passwd.5.gz
shadow /usr/share/man/cs/man5/shadow.5.gz
shadow /usr/share/man/cs/man8/
shadow /usr/share/man/cs/man8/faillog.8.gz
shadow /usr/share/man/cs/man8/groupadd.8.gz
shadow /usr/share/man/cs/man8/groupdel.8.gz
shadow /usr/share/man/cs/man8/groupmod.8.gz
shadow /usr/share/man/cs/man8/grpck.8.gz
shadow /usr/share/man/cs/man8/lastlog.8.gz
shadow /usr/share/man/da/
shadow /usr/share/man/da/man1/
shadow /usr/share/man/da/man1/groups.1.gz
shadow /usr/share/man/da/man1/sg.1.gz
shadow /usr/share/man/da/man5/
shadow /usr/share/man/da/man5/gshadow.5.gz
shadow /usr/share/man/da/man8/
shadow /usr/share/man/da/man8/groupdel.8.gz
shadow /usr/share/man/de/
shadow /usr/share/man/de/man1/
shadow /usr/share/man/de/man1/chage.1.gz
shadow /usr/share/man/de/man1/expiry.1.gz
shadow /usr/share/man/de/man1/gpasswd.1.gz
shadow /usr/share/man/de/man1/groups.1.gz
shadow /usr/share/man/de/man1/passwd.1.gz
shadow /usr/share/man/de/man1/sg.1.gz
shadow /usr/share/man/de/man3/
shadow /usr/share/man/de/man3/getspnam.3.gz
shadow /usr/share/man/de/man3/shadow.3.gz
shadow /usr/share/man/de/man5/
shadow /usr/share/man/de/man5/faillog.5.gz
shadow /usr/share/man/de/man5/gshadow.5.gz
shadow /usr/share/man/de/man5/login.defs.5.gz
shadow /usr/share/man/de/man5/passwd.5.gz
shadow /usr/share/man/de/man5/shadow.5.gz
shadow /usr/share/man/de/man5/suauth.5.gz
shadow /usr/share/man/de/man8/
shadow /usr/share/man/de/man8/chgpasswd.8.gz
shadow /usr/share/man/de/man8/chpasswd.8.gz
shadow /usr/share/man/de/man8/faillog.8.gz
shadow /usr/share/man/de/man8/groupadd.8.gz
shadow /usr/share/man/de/man8/groupdel.8.gz
shadow /usr/share/man/de/man8/groupmems.8.gz
shadow /usr/share/man/de/man8/groupmod.8.gz
shadow /usr/share/man/de/man8/grpck.8.gz
shadow /usr/share/man/de/man8/grpconv.8.gz
shadow /usr/share/man/de/man8/grpunconv.8.gz
shadow /usr/share/man/de/man8/lastlog.8.gz
shadow /usr/share/man/de/man8/newusers.8.gz
shadow /usr/share/man/de/man8/pwck.8.gz
shadow /usr/share/man/de/man8/pwconv.8.gz
shadow /usr/share/man/de/man8/pwunconv.8.gz
shadow /usr/share/man/de/man8/useradd.8.gz
shadow /usr/share/man/de/man8/userdel.8.gz
shadow /usr/share/man/de/man8/usermod.8.gz
shadow /usr/share/man/fr/
shadow /usr/share/man/fr/man1/
shadow /usr/share/man/fr/man1/chage.1.gz
shadow /usr/share/man/fr/man1/expiry.1.gz
shadow /usr/share/man/fr/man1/gpasswd.1.gz
shadow /usr/share/man/fr/man1/groups.1.gz
shadow /usr/share/man/fr/man1/newgidmap.1.gz
shadow /usr/share/man/fr/man1/newuidmap.1.gz
shadow /usr/share/man/fr/man1/passwd.1.gz
shadow /usr/share/man/fr/man1/sg.1.gz
shadow /usr/share/man/fr/man3/
shadow /usr/share/man/fr/man3/getspnam.3.gz
shadow /usr/share/man/fr/man3/shadow.3.gz
shadow /usr/share/man/fr/man5/
shadow /usr/share/man/fr/man5/faillog.5.gz
shadow /usr/share/man/fr/man5/gshadow.5.gz
shadow /usr/share/man/fr/man5/login.defs.5.gz
shadow /usr/share/man/fr/man5/passwd.5.gz
shadow /usr/share/man/fr/man5/shadow.5.gz
shadow /usr/share/man/fr/man5/suauth.5.gz
shadow /usr/share/man/fr/man5/subgid.5.gz
shadow /usr/share/man/fr/man5/subuid.5.gz
shadow /usr/share/man/fr/man8/
shadow /usr/share/man/fr/man8/chgpasswd.8.gz
shadow /usr/share/man/fr/man8/chpasswd.8.gz
shadow /usr/share/man/fr/man8/faillog.8.gz
shadow /usr/share/man/fr/man8/groupadd.8.gz
shadow /usr/share/man/fr/man8/groupdel.8.gz
shadow /usr/share/man/fr/man8/groupmems.8.gz
shadow /usr/share/man/fr/man8/groupmod.8.gz
shadow /usr/share/man/fr/man8/grpck.8.gz
shadow /usr/share/man/fr/man8/grpconv.8.gz
shadow /usr/share/man/fr/man8/grpunconv.8.gz
shadow /usr/share/man/fr/man8/lastlog.8.gz
shadow /usr/share/man/fr/man8/newusers.8.gz
shadow /usr/share/man/fr/man8/pwck.8.gz
shadow /usr/share/man/fr/man8/pwconv.8.gz
shadow /usr/share/man/fr/man8/pwunconv.8.gz
shadow /usr/share/man/fr/man8/useradd.8.gz
shadow /usr/share/man/fr/man8/userdel.8.gz
shadow /usr/share/man/fr/man8/usermod.8.gz
shadow /usr/share/man/hu/
shadow /usr/share/man/hu/man1/
shadow /usr/share/man/hu/man1/gpasswd.1.gz
shadow /usr/share/man/hu/man1/groups.1.gz
shadow /usr/share/man/hu/man1/passwd.1.gz
shadow /usr/share/man/hu/man1/sg.1.gz
shadow /usr/share/man/hu/man5/
shadow /usr/share/man/hu/man5/passwd.5.gz
shadow /usr/share/man/hu/man8/
shadow /usr/share/man/hu/man8/lastlog.8.gz
shadow /usr/share/man/id/
shadow /usr/share/man/id/man8/
shadow /usr/share/man/id/man8/useradd.8.gz
shadow /usr/share/man/it/
shadow /usr/share/man/it/man1/
shadow /usr/share/man/it/man1/chage.1.gz
shadow /usr/share/man/it/man1/expiry.1.gz
shadow /usr/share/man/it/man1/gpasswd.1.gz
shadow /usr/share/man/it/man1/groups.1.gz
shadow /usr/share/man/it/man1/passwd.1.gz
shadow /usr/share/man/it/man1/sg.1.gz
shadow /usr/share/man/it/man3/
shadow /usr/share/man/it/man3/getspnam.3.gz
shadow /usr/share/man/it/man3/shadow.3.gz
shadow /usr/share/man/it/man5/
shadow /usr/share/man/it/man5/faillog.5.gz
shadow /usr/share/man/it/man5/gshadow.5.gz
shadow /usr/share/man/it/man5/login.defs.5.gz
shadow /usr/share/man/it/man5/passwd.5.gz
shadow /usr/share/man/it/man5/shadow.5.gz
shadow /usr/share/man/it/man5/suauth.5.gz
shadow /usr/share/man/it/man8/
shadow /usr/share/man/it/man8/chgpasswd.8.gz
shadow /usr/share/man/it/man8/chpasswd.8.gz
shadow /usr/share/man/it/man8/faillog.8.gz
shadow /usr/share/man/it/man8/groupadd.8.gz
shadow /usr/share/man/it/man8/groupdel.8.gz
shadow /usr/share/man/it/man8/groupmems.8.gz
shadow /usr/share/man/it/man8/groupmod.8.gz
shadow /usr/share/man/it/man8/grpck.8.gz
shadow /usr/share/man/it/man8/grpconv.8.gz
shadow /usr/share/man/it/man8/grpunconv.8.gz
shadow /usr/share/man/it/man8/lastlog.8.gz
shadow /usr/share/man/it/man8/newusers.8.gz
shadow /usr/share/man/it/man8/pwck.8.gz
shadow /usr/share/man/it/man8/pwconv.8.gz
shadow /usr/share/man/it/man8/pwunconv.8.gz
shadow /usr/share/man/it/man8/useradd.8.gz
shadow /usr/share/man/it/man8/userdel.8.gz
shadow /usr/share/man/it/man8/usermod.8.gz
shadow /usr/share/man/ja/
shadow /usr/share/man/ja/man1/
shadow /usr/share/man/ja/man1/chage.1.gz
shadow /usr/share/man/ja/man1/expiry.1.gz
shadow /usr/share/man/ja/man1/gpasswd.1.gz
shadow /usr/share/man/ja/man1/groups.1.gz
shadow /usr/share/man/ja/man1/passwd.1.gz
shadow /usr/share/man/ja/man1/sg.1.gz
shadow /usr/share/man/ja/man5/
shadow /usr/share/man/ja/man5/faillog.5.gz
shadow /usr/share/man/ja/man5/login.defs.5.gz
shadow /usr/share/man/ja/man5/passwd.5.gz
shadow /usr/share/man/ja/man5/shadow.5.gz
shadow /usr/share/man/ja/man5/suauth.5.gz
shadow /usr/share/man/ja/man8/
shadow /usr/share/man/ja/man8/chpasswd.8.gz
shadow /usr/share/man/ja/man8/faillog.8.gz
shadow /usr/share/man/ja/man8/groupadd.8.gz
shadow /usr/share/man/ja/man8/groupdel.8.gz
shadow /usr/share/man/ja/man8/groupmod.8.gz
shadow /usr/share/man/ja/man8/grpck.8.gz
shadow /usr/share/man/ja/man8/grpconv.8.gz
shadow /usr/share/man/ja/man8/grpunconv.8.gz
shadow /usr/share/man/ja/man8/lastlog.8.gz
shadow /usr/share/man/ja/man8/newusers.8.gz
shadow /usr/share/man/ja/man8/pwck.8.gz
shadow /usr/share/man/ja/man8/pwconv.8.gz
shadow /usr/share/man/ja/man8/pwunconv.8.gz
shadow /usr/share/man/ja/man8/useradd.8.gz
shadow /usr/share/man/ja/man8/userdel.8.gz
shadow /usr/share/man/ja/man8/usermod.8.gz
shadow /usr/share/man/ko/
shadow /usr/share/man/ko/man1/
shadow /usr/share/man/ko/man1/groups.1.gz
shadow /usr/share/man/ko/man5/
shadow /usr/share/man/ko/man5/passwd.5.gz
shadow /usr/share/man/man1/
shadow /usr/share/man/man1/chage.1.gz
shadow /usr/share/man/man1/expiry.1.gz
shadow /usr/share/man/man1/gpasswd.1.gz
shadow /usr/share/man/man1/groups.1.gz
shadow /usr/share/man/man1/newgidmap.1.gz
shadow /usr/share/man/man1/newuidmap.1.gz
shadow /usr/share/man/man1/passwd.1.gz
shadow /usr/share/man/man1/sg.1.gz
shadow /usr/share/man/man3/
shadow /usr/share/man/man3/getspnam.3.gz
shadow /usr/share/man/man3/shadow.3.gz
shadow /usr/share/man/man5/
shadow /usr/share/man/man5/faillog.5.gz
shadow /usr/share/man/man5/gshadow.5.gz
shadow /usr/share/man/man5/login.defs.5.gz
shadow /usr/share/man/man5/passwd.5.gz
shadow /usr/share/man/man5/shadow.5.gz
shadow /usr/share/man/man5/suauth.5.gz
shadow /usr/share/man/man5/subgid.5.gz
shadow /usr/share/man/man5/subuid.5.gz
shadow /usr/share/man/man8/
shadow /usr/share/man/man8/chgpasswd.8.gz
shadow /usr/share/man/man8/chpasswd.8.gz
shadow /usr/share/man/man8/faillog.8.gz
shadow /usr/share/man/man8/groupadd.8.gz
shadow /usr/share/man/man8/groupdel.8.gz
shadow /usr/share/man/man8/groupmems.8.gz
shadow /usr/share/man/man8/groupmod.8.gz
shadow /usr/share/man/man8/grpck.8.gz
shadow /usr/share/man/man8/grpconv.8.gz
shadow /usr/share/man/man8/grpunconv.8.gz
shadow /usr/share/man/man8/lastlog.8.gz
shadow /usr/share/man/man8/newusers.8.gz
shadow /usr/share/man/man8/pwck.8.gz
shadow /usr/share/man/man8/pwconv.8.gz
shadow /usr/share/man/man8/pwunconv.8.gz
shadow /usr/share/man/man8/useradd.8.gz
shadow /usr/share/man/man8/userdel.8.gz
shadow /usr/share/man/man8/usermod.8.gz
shadow /usr/share/man/pl/
shadow /usr/share/man/pl/man1/
shadow /usr/share/man/pl/man1/chage.1.gz
shadow /usr/share/man/pl/man1/expiry.1.gz
shadow /usr/share/man/pl/man1/groups.1.gz
shadow /usr/share/man/pl/man1/sg.1.gz
shadow /usr/share/man/pl/man3/
shadow /usr/share/man/pl/man3/getspnam.3.gz
shadow /usr/share/man/pl/man3/shadow.3.gz
shadow /usr/share/man/pl/man5/
shadow /usr/share/man/pl/man5/faillog.5.gz
shadow /usr/share/man/pl/man8/
shadow /usr/share/man/pl/man8/faillog.8.gz
shadow /usr/share/man/pl/man8/groupadd.8.gz
shadow /usr/share/man/pl/man8/groupdel.8.gz
shadow /usr/share/man/pl/man8/groupmems.8.gz
shadow /usr/share/man/pl/man8/groupmod.8.gz
shadow /usr/share/man/pl/man8/grpck.8.gz
shadow /usr/share/man/pl/man8/lastlog.8.gz
shadow /usr/share/man/pl/man8/userdel.8.gz
shadow /usr/share/man/pl/man8/usermod.8.gz
shadow /usr/share/man/pt_BR/
shadow /usr/share/man/pt_BR/man1/
shadow /usr/share/man/pt_BR/man1/gpasswd.1.gz
shadow /usr/share/man/pt_BR/man5/
shadow /usr/share/man/pt_BR/man5/passwd.5.gz
shadow /usr/share/man/pt_BR/man5/shadow.5.gz
shadow /usr/share/man/pt_BR/man8/
shadow /usr/share/man/pt_BR/man8/groupadd.8.gz
shadow /usr/share/man/pt_BR/man8/groupdel.8.gz
shadow /usr/share/man/pt_BR/man8/groupmod.8.gz
shadow /usr/share/man/ru/
shadow /usr/share/man/ru/man1/
shadow /usr/share/man/ru/man1/chage.1.gz
shadow /usr/share/man/ru/man1/expiry.1.gz
shadow /usr/share/man/ru/man1/gpasswd.1.gz
shadow /usr/share/man/ru/man1/groups.1.gz
shadow /usr/share/man/ru/man1/passwd.1.gz
shadow /usr/share/man/ru/man1/sg.1.gz
shadow /usr/share/man/ru/man3/
shadow /usr/share/man/ru/man3/getspnam.3.gz
shadow /usr/share/man/ru/man3/shadow.3.gz
shadow /usr/share/man/ru/man5/
shadow /usr/share/man/ru/man5/faillog.5.gz
shadow /usr/share/man/ru/man5/gshadow.5.gz
shadow /usr/share/man/ru/man5/login.defs.5.gz
shadow /usr/share/man/ru/man5/passwd.5.gz
shadow /usr/share/man/ru/man5/shadow.5.gz
shadow /usr/share/man/ru/man5/suauth.5.gz
shadow /usr/share/man/ru/man8/
shadow /usr/share/man/ru/man8/chgpasswd.8.gz
shadow /usr/share/man/ru/man8/chpasswd.8.gz
shadow /usr/share/man/ru/man8/faillog.8.gz
shadow /usr/share/man/ru/man8/groupadd.8.gz
shadow /usr/share/man/ru/man8/groupdel.8.gz
shadow /usr/share/man/ru/man8/groupmems.8.gz
shadow /usr/share/man/ru/man8/groupmod.8.gz
shadow /usr/share/man/ru/man8/grpck.8.gz
shadow /usr/share/man/ru/man8/grpconv.8.gz
shadow /usr/share/man/ru/man8/grpunconv.8.gz
shadow /usr/share/man/ru/man8/lastlog.8.gz
shadow /usr/share/man/ru/man8/newusers.8.gz
shadow /usr/share/man/ru/man8/pwck.8.gz
shadow /usr/share/man/ru/man8/pwconv.8.gz
shadow /usr/share/man/ru/man8/pwunconv.8.gz
shadow /usr/share/man/ru/man8/useradd.8.gz
shadow /usr/share/man/ru/man8/userdel.8.gz
shadow /usr/share/man/ru/man8/usermod.8.gz
shadow /usr/share/man/sv/
shadow /usr/share/man/sv/man1/
shadow /usr/share/man/sv/man1/chage.1.gz
shadow /usr/share/man/sv/man1/expiry.1.gz
shadow /usr/share/man/sv/man1/groups.1.gz
shadow /usr/share/man/sv/man1/passwd.1.gz
shadow /usr/share/man/sv/man1/sg.1.gz
shadow /usr/share/man/sv/man3/
shadow /usr/share/man/sv/man3/getspnam.3.gz
shadow /usr/share/man/sv/man3/shadow.3.gz
shadow /usr/share/man/sv/man5/
shadow /usr/share/man/sv/man5/faillog.5.gz
shadow /usr/share/man/sv/man5/gshadow.5.gz
shadow /usr/share/man/sv/man5/passwd.5.gz
shadow /usr/share/man/sv/man5/suauth.5.gz
shadow /usr/share/man/sv/man8/
shadow /usr/share/man/sv/man8/faillog.8.gz
shadow /usr/share/man/sv/man8/groupadd.8.gz
shadow /usr/share/man/sv/man8/groupdel.8.gz
shadow /usr/share/man/sv/man8/groupmems.8.gz
shadow /usr/share/man/sv/man8/groupmod.8.gz
shadow /usr/share/man/sv/man8/grpck.8.gz
shadow /usr/share/man/sv/man8/lastlog.8.gz
shadow /usr/share/man/sv/man8/pwck.8.gz
shadow /usr/share/man/sv/man8/userdel.8.gz
shadow /usr/share/man/tr/
shadow /usr/share/man/tr/man1/
shadow /usr/share/man/tr/man1/chage.1.gz
shadow /usr/share/man/tr/man1/passwd.1.gz
shadow /usr/share/man/tr/man5/
shadow /usr/share/man/tr/man5/passwd.5.gz
shadow /usr/share/man/tr/man5/shadow.5.gz
shadow /usr/share/man/tr/man8/
shadow /usr/share/man/tr/man8/groupadd.8.gz
shadow /usr/share/man/tr/man8/groupdel.8.gz
shadow /usr/share/man/tr/man8/groupmod.8.gz
shadow /usr/share/man/tr/man8/useradd.8.gz
shadow /usr/share/man/tr/man8/userdel.8.gz
shadow /usr/share/man/tr/man8/usermod.8.gz
shadow /usr/share/man/zh_CN/
shadow /usr/share/man/zh_CN/man1/
shadow /usr/share/man/zh_CN/man1/chage.1.gz
shadow /usr/share/man/zh_CN/man1/expiry.1.gz
shadow /usr/share/man/zh_CN/man1/gpasswd.1.gz
shadow /usr/share/man/zh_CN/man1/groups.1.gz
shadow /usr/share/man/zh_CN/man1/passwd.1.gz
shadow /usr/share/man/zh_CN/man1/sg.1.gz
shadow /usr/share/man/zh_CN/man3/
shadow /usr/share/man/zh_CN/man3/getspnam.3.gz
shadow /usr/share/man/zh_CN/man3/shadow.3.gz
shadow /usr/share/man/zh_CN/man5/
shadow /usr/share/man/zh_CN/man5/faillog.5.gz
shadow /usr/share/man/zh_CN/man5/gshadow.5.gz
shadow /usr/share/man/zh_CN/man5/login.defs.5.gz
shadow /usr/share/man/zh_CN/man5/passwd.5.gz
shadow /usr/share/man/zh_CN/man5/shadow.5.gz
shadow /usr/share/man/zh_CN/man5/suauth.5.gz
shadow /usr/share/man/zh_CN/man8/
shadow /usr/share/man/zh_CN/man8/chgpasswd.8.gz
shadow /usr/share/man/zh_CN/man8/chpasswd.8.gz
shadow /usr/share/man/zh_CN/man8/faillog.8.gz
shadow /usr/share/man/zh_CN/man8/groupadd.8.gz
shadow /usr/share/man/zh_CN/man8/groupdel.8.gz
shadow /usr/share/man/zh_CN/man8/groupmems.8.gz
shadow /usr/share/man/zh_CN/man8/groupmod.8.gz
shadow /usr/share/man/zh_CN/man8/grpck.8.gz
shadow /usr/share/man/zh_CN/man8/grpconv.8.gz
shadow /usr/share/man/zh_CN/man8/grpunconv.8.gz
shadow /usr/share/man/zh_CN/man8/lastlog.8.gz
shadow /usr/share/man/zh_CN/man8/newusers.8.gz
shadow /usr/share/man/zh_CN/man8/pwck.8.gz
shadow /usr/share/man/zh_CN/man8/pwconv.8.gz
shadow /usr/share/man/zh_CN/man8/pwunconv.8.gz
shadow /usr/share/man/zh_CN/man8/useradd.8.gz
shadow /usr/share/man/zh_CN/man8/userdel.8.gz
shadow /usr/share/man/zh_CN/man8/usermod.8.gz
shadow /usr/share/man/zh_TW/
shadow /usr/share/man/zh_TW/man5/
shadow /usr/share/man/zh_TW/man5/passwd.5.gz
shadow /usr/share/man/zh_TW/man8/
shadow /usr/share/man/zh_TW/man8/chpasswd.8.gz
shadow /usr/share/man/zh_TW/man8/groupadd.8.gz
shadow /usr/share/man/zh_TW/man8/groupdel.8.gz
shadow /usr/share/man/zh_TW/man8/groupmod.8.gz
shadow /usr/share/man/zh_TW/man8/useradd.8.gz
shadow /usr/share/man/zh_TW/man8/userdel.8.gz
shadow /usr/share/man/zh_TW/man8/usermod.8.gz
