.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RONN\-FOMART" "7" "February 2015" "" ""
.
.SH "NAME"
\fBronn\-fomart\fR \- 基于markdown的手册编写格式
.
.SH "描述"
\fBronn\fR命令可以将注释文本转化成\fBman\fR手册页，\fBronn\-format\fR包含markdown格式 的所有特性，同还引入了一些其他在\fBman\fR手册中使用的约定和标记。注意， \fBronn\-format\fR并不包含所有的\fBroff\fR格式特性。
.
.SH "手册标题"
手册标题由名称、类别和一行描述性文本组成，文件必须以Setext中最高阶标题的 形式开始。如下范例：
.
.IP "" 4
.
.nf

ls(1) \-\- list directory contents
================================
.
.fi
.
.IP "" 0
.
.SH "章节标题"
章节标题可以用\fBmarkdown\fR语法中的二级类atx形式或者二阶类\fBSetext\fR形式。如下 范例：
.
.IP "" 4
.
.nf

##HEADING TEXT
或者
HEADING TEXT
\-\-\-\-\-\-\-\-\-\-\-\-
.
.fi
.
.IP "" 0
.
.SH "行内标记"
通常\fBman\fR手册使用的加粗、斜体和下划线，\fBronn\fR使用如下语法来完成。
.
.TP
`\fB反斜杠\fR`
兼容\fBMarkdown\fR,反斜杠可以用来包裹代码、标志、命令符和其他 类似物，在\fBman\fR中表现为粗体，HTML代码为\fB<code>\fR。
.
.TP
**\fB双星\fR**
兼容\fBMarkdown\fR,同样表现为粗体，与反斜杠不同，其内部使 用的标志语言依然会被识别，\fBHTML\fR代码为\fB<strong>\fR。
.
.TP
\fI<尖括号\fR>
不兼容\fBMarkdown\fR,该自定义标志内部文本表现为文本下添加了下划 线，在网页中显为斜体，\fBHTML\fR代码为\fB<var/>\fR。
.
.TP
_\fI下划线\fR_
兼容Markdown,强调，可以用来表示选项参数，表现为文本下添加 下划线，HTML代码为\fB<em>\fR。
.
.P
下面例子使用ronn语法来表示Grep(1)的描述行：
.
.IP "" 4
.
.nf

`Grep` searches the named input <FILE> (or standard input if
no files are named, or the file name `\-` is given) for lines
containing a match to the given <PATTERN>\. By default, `grep`
prints the matching lines\.
.
.fi
.
.IP "" 0
.
.SH "列表"
在ronn中定义列表的方式同\fBMarkdown\fR一致，但是要求列表的第一行以分号\fB:\fR结 束，此后可以包含段落，代码和嵌套列表等。下面以BSD test的\fBDESCRIPTION\fR为 例。
.
.IP "" 4
.
.nf

* `\-b` <file>:
True if <file> exists and is a block special file\.

* `\-c` <file>:
True if _file_ exists and is a character special file\.

* `\-d` <file>:
True if file exists and is a directory\.
.
.fi
.
.IP "" 0
.
.SH "链接"
ronn支持所有markdown的链接特点。
.
.IP "" 4
.
.nf

## SECTION 1

See the following section\.

## SECTION 2

See [SECTION 1][] or [to put it another way][SECTION 1]\.
.
.fi
.
.IP "" 0
.
.SH "更多SEE ALSO"
ronn(1), markdown(7), roff(7)
